# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
